; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	d:\dev\projects\sooty\trunk\project\sooty_test\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT

PUBLIC	_main
; Function compile flags: /Odtpy
; File d:\dev\projects\sooty\trunk\project\sooty_test\main.cpp
_TEXT	SEGMENT
_i$ = -4						; size = 4
_main	PROC

; 2    : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 3    : 	int i = 0;

	mov	DWORD PTR _i$[ebp], 0

; 4    : 	return i;

	mov	eax, DWORD PTR _i$[ebp]

; 5    : }

	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
